server:
    port: 8081

camel:
  springboot:
    tracing: false
    tracing-standby: false

input:
  dir: /tmp/camel
  file: test.txt

output:
  dir: /tmp/camel/out

gwh:
  group:
    count: 3
  core:
    db:
      datasource:
        className: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.6.2:3306/gwh
        userName: root        
        minpoolsize: 0
        maxpoolsize: 50
        increment: 2
        maxidleTime: 300
        retryDelay: 600000                
        jpa-dialect: org.hibernate.dialect.MySQLDialect        
        jpa-ddl-auto: validate          
        jpa-physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  activemqtest:
    component:
      broker-url: tcp://192.168.6.1:61616
      username: artemis
      password: artemis
      session-cache-size: 10

  framework:
    routes:
      load:
        params:
          enabled: true
    component:
      activemqtest:
        enabled: true
      kafka:
        enabled: true

debug: false

logging:
  level:
    root: INFO
    org:
      apache:
        camel: INFO
          #component:
          #  ftp: TRACE      
        commons:
          net: TRACE
      springframework:
        transaction: 
          interceptor: TRACE
        #web: DEBUG
      #hibernate:
      #  SQL: DEBUG
      #  type:
      #    descriptor:
      #      sql:
      #      BasicBinder: TRACE